# Generated by Django 3.2.23 on 2023-12-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0003_employeeeducation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedetail',
            old_name='destination',
            new_name='designation',
        ),
    ]
