# Generated by Django 3.2.23 on 2023-12-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0005_auto_20231201_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='gender',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
