# Generated by Django 4.2.7 on 2023-11-23 18:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeData',
            new_name='EmployeeDetail',
        ),
    ]
