# Generated by Django 4.2.7 on 2023-11-27 17:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HR_app', '0003_employeeeeperience_employeeeducation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeEeperience',
            new_name='EmployeeExperience',
        ),
    ]
